### ISSUE TITLE
Multiple Peers within same thread

### ISSUE THREAD

**Issue by ClosetMonkey** [rawrtc/rawrtc#120]
I'm investigation multiple libraries right now so please forgive me if this is obviously with enough code surfing, but is an rawrtc peer able to connect to multiple remote peers within same thread/process, or will a new local peer need to be spawned for every new remote peer connection?

**Comment by lgrahl** [comment]
You can have multiple peers running on the same thread (this is event looped).
You could spawn more peers from a single ICE gatherer in order to create multiple peer connections (this is called ICE forking) but I haven't investigated whether that is supported by rew, so it's not there right now. For now, you create an ICE gatherer per peer connection (which should not be considerably more code).

For general questions, it would be easier to ask [here](https://gitter.im/rawrtc/Lobby) in the future.
