### ISSUE TITLE
rawrtc spend too much memory

### ISSUE THREAD

**Issue by lxlenovostar** [rawrtc/rawrtc#123]
I use rawrtc on ARM/openwrt.  In the begin, the process need 30MB memory. When we build p2p connection with 30 clients, the memory is 100MB.  How to analysis which places consume too much memory?  @lgrahl

**Comment by lgrahl** [comment]
That is most likely due to the amount of streams allocated (see https://github.com/sctplab/usrsctp/issues/121).

You can change the amount of allocated streams by swapping the constant with something hard-coded. https://github.com/rawrtc/rawrtc/blob/master/src/librawrtc/sctp_transport.c#L1976

Closed in favour of #124. Feel free to reopen if you still see a lot of memory allocated after changing this.
