### ISSUE TITLE
How to try?

### ISSUE THREAD

**Issue by dbrgn** [rawrtc/rawrtc#4]
Would be great to have instructions in README on how to try this project. I can run `data-channel-sctp` as documented, but I get no explanation what actually happens.

A quick browser-interop example would probably be the most interesting aspect that could be documented.

**Comment by lgrahl** [comment]
Yes, indeed, documentation is pretty bad at the moment. You can check out browser interop by opening [htdocs/webrtc-rawrtc.html](./htdocs/webrtc-rawrtc.html) in your browser:

1. Open the developer console in the browser.
2. Copy & paste the JSON output from the browser into the `data-channel-sctp` tool.
3. Copy & paste the JSON output from the `data-channel-sctp` tool into the browser.
4. Press the `Start` button in the browser.
5. Quickly press `Enter` in the `data-channel-sctp` tool (or ICE may go to failed if you're too slow).
6. Use the created data channels in the browser console by accessing `peer.dc['<channel-name>']`, for example `peer.dc['<channel-name>'].send('RAWR!')`.

The same can be done for two `data-channel-sctp` instances instead of the browser. It should be fairly straight-forward.

You can also use the `data-channel-sctp-echo` tool to echo data back to the browser.

**Comment by dbrgn** [comment]
Docs on how to use rawrtc as a library would also be great (maybe with a C code example).

**Comment by lgrahl** [comment]
Yes, I think we'll move the `data-channel-sctp-ws-terminal` tool from the `simple-ws-signaling` branch into a separate repository as a usage example. Btw. this tool is the backend for the terminal demo.

**Comment by lgrahl** [comment]
I have moved the library usage part into #15

**Comment by Globik** [comment]
Where is a websocket?

**Comment by lgrahl** [comment]
Sorry, I don't understand your question.
